[package]
version = "2.0.0"
title = "Vehicle Path Tracking"
description = "Enables omni.physxvehicle prims to autonomously follow user-defined BasisCurve trajectories using the Pure Pursuit algorithm."
readme = "docs/CHANGELOG.md"
icon = "data/icon.png"
keywords = ["kit", "vehicle", "path", "tracking", "physx", "pure pursuit", "autonomous"]
category = "Simulation"

[dependencies]
"omni.usd" = {}
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.vehicle" = {}
"omni.usdphysics" = {}
"omni.kit.viewport.utility" = {}

[[python.module]]
name = "path.tracking.sim"

[[test]]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]

dependencies = [
    "omni.hydra.pxr",
    "omni.kit.mainwindow",
    "omni.kit.widget.stage",
    "omni.kit.window.viewport",
    "omni.kit.window.stage",
    "omni.kit.test_suite.helpers",
]
